name: Build & Release FrankOS

on:
  push:
    branches: [main]
  workflow_dispatch:
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: pacman -Sy --noconfirm xorriso
      
      - name: Install arch-install-scripts
        run: pacman -Sy --noconfirm arch-install-scripts

      
      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Run build
        run: ./build.sh

      - name: Publish ISO
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.iso
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: frankos-minimal-v0.1.0
