name: Build & Release FrankOS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo pacman -Sy --noconfirm xorriso

      - name: Make build.sh executable
        run: chmod +x build.sh

      - name: Run build
        run: ./build.sh

      - name: Publish ISO
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.iso
